[build]
publish = "_site"
command = "npm run build"

# Content negotiation for home page
[[redirects]]
from = "/"
to = "/nl-NL/"
status = 200
conditions = {Language = ["nl-NL"]}

# Content negotiation for home page
[[redirects]]
from = "/"
to = "/en-US/"
status = 200

# Redirect for end-user’s browser preference override
[[redirects]]
from = "/*"
to = "/nl-NL/:splat"
status = 302
conditions = {Language = ["nl-NL"]}

# Default
[[redirects]]
from = "/*"
to = "/en-US/:splat"
status = 302
